require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IssuesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ticket. As you add validations to Ticket, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString", "header" => "TestHeader", "email" => "test@example.com" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TicketsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "index" do
    it "assigns all tickets as @tickets" do
      issue = Issue.create! valid_attributes
      get :index, {}, valid_session
      expect(Issue.all).to eq([issue])
    end
  end

  describe "show" do
    it "assigns the requested ticket as @ticket" do
      issue = Issue.create! valid_attributes
      get :show, {:id => issue.to_param}, valid_session
      expect(Issue.all.last).to eq(issue)
    end
  end

  describe "GET new" do
    it "assigns a new ticket as @ticket" do
      get :new, {}, valid_session
      expect(assigns(:issue)).to be_a_new(Issue)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket as @ticket" do
      issue = Issue.create! valid_attributes
      get :edit, {:id => issue.to_param}, valid_session
      assigns(:issue).should eq(issue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ticket" do
        expect {
          post :create, {:issue => valid_attributes}, valid_session
        }.to change(Issue, :count).by(1)
      end

      it "assigns a newly created ticket as @ticket" do
        post :create, {:issue => valid_attributes}, valid_session
        assigns(:issue).should be_a(Issue)
        assigns(:issue).should be_persisted
      end

      it "redirects to the created ticket" do
        post :create, {:issue => valid_attributes}, valid_session
        response.should redirect_to(Issue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket as @ticket" do
        # Trigger the behavior that occurs when invalid params are submitted
        Issue.any_instance.stub(:save).and_return(false)
        post :create, {:issue => { "name" => "invalid value" }}, valid_session
        assigns(:issue).should be_a_new(Issue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Issue.any_instance.stub(:save).and_return(false)
        post :create, {:issue => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "assigns the requested ticket as @ticket" do
        issue = Issue.create! valid_attributes
        put :update, {:id => issue.to_param, :issue => { "name" => "invalid value", :reply => { "body" => "hello"}}}, valid_session
        assigns(:issue).should eq(issue)
      end

      it "redirects to the ticket" do
        issue = Issue.create! valid_attributes
        put :update, {:id => issue.to_param, :issue => { "name" => "invalid value", :reply => { "body" => "hello"}}}, valid_session
        response.should redirect_to(issue)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket as @ticket" do
        issue = Issue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Issue.any_instance.stub(:save).and_return(false)
        put :update, {:id => issue.to_param, :issue => { "name" => "invalid value" }}, valid_session
        assigns(:issue).should eq(issue)
      end

      it "re-renders the 'edit' template" do
        issue = Issue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Issue.any_instance.stub(:save).and_return(false)
        put :update, {:id => issue.to_param, :issue => { "name" => "invalid value", :reply => { "body" => "hello"}}}, valid_session
        response.should render_template("edit")
      end
    end
  end

end
